# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20a3301507b3df180f8154b1e852b26bcc80fb5965b254d3e550752ed217514f511029402e212e38c980228d2e40ef255893333d3c82a8d97949e1cceaf8d378

test:
  secret_key_base: 00216e3ed7b87bc43cf4791df8ae160d9917f2aab183d0f74a64ef9b48c40041647c15bbd482f11d1778d57201ed32b1e4076b8f9f7266d8ce2bf06db8313171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
